# **DESCRIPCION DEL DATASET ORIGINAL**

El dataset corresponde a una matriz de seguimiento de cumplimiento ambiental, cuyo objetivo es consolidar en un único archivo los distintos compromisos y requisitos legales asociados a una operación.

La estructura original presenta un enfoque monolítico, donde múltiples tipos de información (permisos, estados, responsables, fechas y observaciones) se agrupan en una sola tabla con atributos ambivalentes que dificultan su análisis.

Adicionalmente, existen hojas complementarias que replican información a mayor nivel de detalle por componente ambiental, generando redundancia y posibles inconsistencias.

## **OBJETIVO DEL DATA ANALISIS REALIZADO**



1.   Transformar estructura caotica a modelo analitico
2.   Reducir redundancia
3.   Facilitar el analisis del cumplimiento
4.   Generar KPIs claros
5.   Creacion  de Dashboard en Power BI

## **CARGA DE DATOS**

In [ ]:
import os
import pandas as pd

ruta = '/content/drive/MyDrive/DATA_SET_PROJECTS/ambiental_data.xlsx'

if os.path.exists(ruta):
    df = pd.read_excel(ruta)
    print("Archivo cargado desde Drive")
else:
    print("Sube el archivo o ajusta la ruta")

Archivo cargado desde Drive

## **EXPLORACION DE DATAFRAME**

In [ ]:
# Vista previa
df.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,Fecha actualizacion,2023-02-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Rev,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,PROYECTO,CONSTRUCCION ASTILLERO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,AREA,Medio Ambiente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,ENCARGADO,Nombre Ejemplo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,N°,Componente,Faena,Tipo de Tarea,Descripcion,Documento /Accion,Periodicidad,Entregables,Resultado,Etapa Proyecto,Area Responsable,Observaciones,NaN,NaN
7,1,Obras,Ejecución de tronaduras,Plan/Informe,Contar con plan detallado de tronaduras en bas...,Plan detallado de tronaduras,Una vez,1,1,Antes del inicio de fase de perforación y tron...,Oficina Tecnica,NaN,NaN,NaN
8,2,Obras,Ejecución de tronaduras,Gestion /Autorizacion,Aspectos mínimos del plan de tronaduras,Autorización de consumidor de explosivos.\nAut...,Una vez,3,2,Antes del inicio de fase de perforación y tron...,Calidad,NaN,NaN,NaN
9,3,Obras,Ejecución de tronaduras,Procedimiento/Informe,Contratista debe contar con procedimiento de t...,Procedimiento de transporte de explosivos.\nPr...,Una vez,3,3,Antes del inicio de fase de perforación y tron...,Prevencion/Medioambiente,NaN,NaN,NaN

In [ ]:
df.tail()

### **PREPROCESAMIENTO INICIAL**

Se eliminan las primeras filas del archivo debido a que contienen información no estructurada (títulos, encabezados visuales, etc.), permitiendo identificar correctamente las columnas de datos.

In [ ]:
df = df.iloc[6:]
df.columns = df.iloc[0]
df = df.iloc[1:]

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df.columns

## **TRANSFORMACIONES**

“Despues de la exploracion inicial se procede con la limpieza, normalización y estructuración del dataset para su posterior análisis.”

Se identificaron múltiples deficiencias en el diseño original de la tabla, incluyendo:

- Violaciones a la 1NF (atributos no atómicos)
- Redundancia semántica entre columnas
- Uso de descripciones en lugar de categorías
- Columnas sin valor analítico

Se procede a rediseñar la estructura del dataset, eliminando columnas irrelevantes, renombrando variables para mayor claridad y creando nuevas columnas orientadas a un modelo relacional futuro (Documentos y Observaciones).

### **LIMPIEZA DE FILAS Y COLUMNAS VACIAS O SUCIAS**

Se eliminaran las ultimas 2 filas de la tabla, y las 2 ultimas columnas hacia la derecha
 ya que no poseen valores, o los resulatdos totales bajo las columnas son irrelevantes
 e incompletos

In [ ]:

df = df.iloc[:-2]
df = df.iloc[:,:-2]

In [ ]:
df.head()

In [ ]:
df.tail(5)

6,N°,Componente,Faena,Tipo de Tarea,Descripcion,Documento /Accion,Periodicidad,Entregables,Resultado,Etapa Proyecto,Area Responsable,Observaciones
107,101,sustancias peligrosas,Manejo de combustibles,Procedimiento/Informe,Usar equipos y contenedores adecuados para con...,Procedimiento de trasvasije de combustible.\nR...,trimestral,4,3,Durante fase de construcción,NaN,NaN
108,102,General,"Informar a SMA gestión, acto o faena mínima d...",Respaldo/Informe,"Informar a SMA la realización de gestión, acto...",Respaldo de informe de ejecución de faena míni...,Una vez,1,1,Al inicio de fase de construcción,NaN,NaN
109,103,General,Informar a SMA inicio de fase de construcción,Respaldo/Informe,Informar a SMA inicio de fase de construcción ...,Respaldo de aviso de inicio de fase de constru...,Una vez,1,1,Al menos una semana antes del inicio de la fas...,NaN,NaN
110,104,General,Entregar Plan de gestion ambiental,Respaldo/Informe,Remitir a EFONSA el plan de gestion ambiental ...,Entrega Informe,Una vez,1,1,NaN,NaN,NaN
111,105,General,Elaborar matriz de seguimiento ambiental,Respaldo/Informe,Remitir a EFONSA matriz de seguimiento ambiental,Entrega Informe,Una vez,1,1,NaN,NaN,NaN

###**ELIMINACION DE COLUMNAS SEGUN NUEVO MODELO**

Periodicidad no es relevante para el analisis de cumplimiento. Sólo se requiere conteo de entregas respecto al total. Tipo de tarea esta mal asociado conceptualmente durante la concepcion del modelo o quedó mal etiquetado.

In [ ]:
df = df.drop(columns=['Periodicidad', 'Tipo de Tarea'])

In [ ]:
df

### **RENOMBRAR COLUMNAS**

In [ ]:
df = df.rename(columns={
    'N°': 'ID',
    'Resultado':'Entregados',
    'Faena':'Actividad',
    'Descripcion ':'Requisito',
    'Documento /Accion':'Detalle_doc'
})

In [ ]:
df

### **CREAR NUEVAS COLUMMNAS**

In [ ]:
df['Documento'] = None
df['Doc_ID'] = None
df['Obs_ID'] = None

### TRANSFORMAR COLUMNA OBSERVACIONES A BOLEANO

In [ ]:
df['Observaciones'] = df['Observaciones'].notna()

### **LIMPIEZA DE ENCABEZADO**

In [ ]:
df.columns = df.columns.str.strip()

### **REORDENAR COLUMNAS**

In [ ]:
df = df[
    ['ID',
     'Etapa Proyecto',
     'Actividad',
     'Area Responsable',
     'Componente',
     'Requisito',
     'Documento',
     'Detalle_doc',
     'Doc_ID',
     'Entregables',
     'Entregados',
     'Observaciones',
     'Obs_ID']
]

In [ ]:
df

visualizacion completa de la tabla

In [ ]:
pd.set_option('display.max_colwidth', None)

In [ ]:
df

6,ID,Etapa Proyecto,Actividad,Area Responsable,Componente,Requisito,Documento,Detalle_doc,Doc_ID,Entregables,Entregados,Observaciones,Obs_ID
7,1,Antes del inicio de fase de perforación y tronaduras,Ejecución de tronaduras,Oficina Tecnica,Obras,Contar con plan detallado de tronaduras en base a investigación geotécnica,None,Plan detallado de tronaduras,None,1,1,False,None
8,2,Antes del inicio de fase de perforación y tronaduras,Ejecución de tronaduras,Calidad,Obras,Aspectos mínimos del plan de tronaduras,None,Autorización de consumidor de explosivos.\nAutorizaciones transporte de Explosivos.\nAutorizaciones polvorines de almacenamiento de explosivos,None,3,2,False,None
9,3,Antes del inicio de fase de perforación y tronaduras,Ejecución de tronaduras,Prevencion/Medioambiente,Obras,"Contratista debe contar con procedimiento de transporte, almacenamiento y manipulación de explosivos",None,Procedimiento de transporte de explosivos.\nProcedimiento de almacenamiento de explosivos\nProcedimiento de manipulación de explosivos.\n,None,3,3,False,None
10,4,Antes del inicio de fase de perforación y tronaduras,Ejecución de tronaduras,NaN,Fauna,"Coordinar con Sernapesca, acuicultura y Seremi MA presencia de inspectores durante desarrollo de tronaduras",None,Registros de comunicación con autoridades correspondientes,None,5,2,False,None
11,5,"Antes de cada tronadura, Durante periodo de ejecución de tronaduras",Ejecución de tronaduras,Prevencion/Medioambiente,Fauna,Contar presencia de inspectores técnicos durante ejecución de tronaduras (según lo resuelto por autoridades),None,Registros de inspección técnica de tronaduras,None,5,3,True,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,101,Durante fase de construcción,Manejo de combustibles,NaN,sustancias peligrosas,Usar equipos y contenedores adecuados para contener derrames durante trasvasije de combustibles,None,Procedimiento de trasvasije de combustible.\nRegistros de inspección de actividad de trasvasije de combustible,None,4,3,False,None
108,102,Al inicio de fase de construcción,"Informar a SMA gestión, acto o faena mínima de inicio de obras",NaN,General,"Informar a SMA la realización de gestión, acto o faena mínima que de cuenta del inicio de obras",None,Respaldo de informe de ejecución de faena mínima de inicio de obras,None,1,1,False,None
109,103,Al menos una semana antes del inicio de la fase de construcción,Informar a SMA inicio de fase de construcción,NaN,General,Informar a SMA inicio de fase de construcción al menos con una semana de anticipación,None,Respaldo de aviso de inicio de fase de construcción,None,1,1,False,None
110,104,NaN,Entregar Plan de gestion ambiental,NaN,General,Remitir a EFONSA el plan de gestion ambiental de la constructora,None,Entrega Informe,None,1,1,False,None
111,105,NaN,Elaborar matriz de seguimiento ambiental,NaN,General,Remitir a EFONSA matriz de seguimiento ambiental,None,Entrega Informe,None,1,1,False,None

## **SUSTITUCION DE CADENAS DE TEXTO LARGAS POR CATEGORIAS CLARAS**

Se identifican múltiples descripciones textuales que hacen referencia a conceptos que pueden resumirse  dentro de categorias tecnicas.

Se procede a normalizar estos valores en categorias  unicas mediante sustitucion de texto con el objetivo de mejorar la consistencia semántica y facilitar el análisis posterior.

### **COLUMNA "Etapa Proyecto"**

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Antes del inicio de fase de perforación y tronaduras', 'Planificacion Tronadura')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Antes de cada tronadura, Durante periodo de ejecución de tronaduras', 'Planificacion Tronadura')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante fase de construcción', 'Toda la operación')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('En cada retiro, Durante fase de construcción', 'Toda la operación')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Al inicio de fase de construcción', 'Preconstruccion')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Al menos una semana antes del inicio de la fase de construcción', 'Preconstruccion')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Antes del inicio de las obras y al ingreso de nuevos trabajadores, Durante toda la fase de construcción que implique remoción de la superficie y excavación sub-superficial en el área del proyecto', 'Preconstruccion')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Hasta 20 días despues de finalizada la obra', 'Cierre de faena')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('30 días despues de finalizada la obra', 'Cierre de faena')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante periodo de ejecución de tronaduras', 'Ejecución Tronadura')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante ejecución de remoción de material y sedimentos (perforación y excavación en mar)', 'Ejecución Tronadura')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Antes de cada tronadura, Durante periodo de ejecución de tronaduras', 'Ejecución Tronadura')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante periodo de ejecución de perforación submarina', 'Perforacion Submarina')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante toda la fase de construcción que implique remoción de la superficie y excavación sub-superficial en el área del proyecto.', 'Excavacion borde costero')

In [55]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('En cada tronadura, Durante perforación y tronaduras', 'Ejecución Tronadura')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Antes del inicio de las obras y al ingreso de nuevos trabajadores, Durante toda la fase de construcción que implique remoción de la superficie y excavación sub-superficial en el área del proyecto.', 'Excavación borde costero')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante fase de construcción, hasta 25 días después de ejecutada la campaña', 'Preconstruccion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('La primera campaña de monitoreo se realizará dos semanas posterior ocurridas las primeras tronaduras, mientras que las siguientes campañas tendrán una frecuencia de monitoreo bimensual, extendiéndose por un período de 10 meses en total, o al término de las tronaduras.', 'Toda la operación')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante fase de construcción, hasta 25 días después de ejecutada la campaña', 'Toda la operacion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Antes del inicio de las obras', 'Preconstruccion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante periodo de construcción que implique ejecución de tronaduras con desvíos de tránsito', 'Ejecución Tronadura')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Diaria, durante el día que se ejecute las Primeras 10 tronaduras.', 'Ejecución Tronadura')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Una vez finalizada las obras ( Tronaduras)', 'Ejecución Tronadura')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante desvíos de tránsito', 'Toda la operacion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Un mes antes del inicio de las obras', 'Preconstruccion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Durante las obras de construcción', 'Preconstruccion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Antes de la intervención del sitio', 'Preconstruccion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Hasta 30 días después de ejecutada la campaña de perturbación', 'Preconstruccion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Hasta 20 días después de ejecutada medida de protección de aves', 'Preconstruccion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Hasta 30 días después de ejecutada la medida de protección de aves', 'Preconstruccion')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('La primera campaña de monitoreo se realizará dos semanas posterior ocurridas las primeras tronaduras, mientras que las siguientes campañas tendrán una frecuencia de monitoreo bimensual, extendiéndose por un período de 10 meses en total.', 'Toda la operación')
df['Etapa Proyecto'] = df['Etapa Proyecto'].replace('Diaria, durante el día que se ejecute las Primeras 10 tronaduras.\nTrimestrales, durante fase de construcción de tronaduras.','Toda la operación')

In [ ]:
df['Etapa Proyecto'] = df['Etapa Proyecto'].fillna('Preconstruccion')
df['Area Responsable'] = df['Area Responsable'].fillna('Oficina Tecnica')

In [ ]:
df['Doc_ID'] = range(1, len(df) + 1)

In [ ]:
df['Obs_ID'] = range(1, len(df) + 1)

In [ ]:
df.tail(50)

## **EXPORTACION DEL DATAFRAME A EXCEL**

In [ ]:
df_nuevo = df.copy()
ruta_salida = '/content/drive/MyDrive/DATA_SET_PROJECTS/modelo_requisitos_v1.xlsx'

df_nuevo.to_excel(ruta_salida, index=False)

#**RESULTADOS DEL ETL**

“El dataset original presentaba una estructura monolítica con redundancias entre hojas, lo que dificultaba su análisis. Mi enfoque fue normalizar la información y estructurarla para permitir un seguimiento eficiente del cumplimiento ambiental.”

La nueva estructura permite evaluar el desempeño en relacion al cumplimiento normativo legal por área o departamento dentro de la empresa, y además por componente ambiental si se requiere.

La nueva estructura permite gestionar los permisos y documentos de manera ordenada en su propia "matriz de permisos", utilizando un ID como clavé foranea que la relaciona con el dataframe principal.

El dashboard automatizado en Power BI sobre el nuevo dataset permite identificar la legislacion mas critica, compleja o con mayor morosidad permitiendo adelantarse a la solicitud de requisitos por parte de la utoridad, ahorrando tiempo de gestion interna empresarial.